# The rest
choco install 7zip
choco install adobereader
choco install anaconda3
choco install battle.net
choco install brave
choco install calibre
choco install ccleaner
choco install conemu
choco install deluge
choco install discord
choco install docker-desktop
choco install firacode
choco install firefox
choco install git
choco install minecraft
choco install nodejs
choco install paint.net
choco install putty
choco install rufus
choco install skype
choco install slack
choco install spotify
choco install spybot
choco install steam
choco install vlc
choco install vscode

# Virtualbox, SLobs