server {
  listen 80;
  listen [::]:80;

  server_name www.blog.jsalv.com;

  location / {
      proxy_pass http://localhost:8106/;
      proxy_buffering off;
      proxy_set_header X-Real-IP $remote_addr;
  }
}

server {
  listen 80;
  listen [::]:80;

  server_name blog.jsalv.com;

  location / {
      proxy_pass http://localhost:8106/;
      proxy_buffering off;
      proxy_set_header X-Real-IP $remote_addr;
  }
}
